"""
AI-Generated Content Detector
Uses RoBERTa-based OpenAI detector + perplexity/burstiness analysis
to determine probability that text was generated by AI (GPT-4, etc.).
"""

import re
import time
import math
import numpy as np
from typing import List, Dict

# Lazy-loaded models
_classifier = None
_tokenizer_gpt2 = None
_model_gpt2 = None


def _get_classifier():
    """Use fast heuristic mode for instant results."""
    global _classifier
    if _classifier is None:
        print("[AI Detector] Using fast heuristic detection mode.")
        _classifier = "HEURISTIC"
    return None  # Always use heuristic for speed


def _get_gpt2_model():
    """Skip heavy model - use statistical estimation."""
    return None, None


def split_into_paragraphs(text: str) -> List[str]:
    """Split text into paragraphs."""
    paragraphs = re.split(r'\n\s*\n|\n', text.strip())
    return [p.strip() for p in paragraphs if len(p.strip()) > 30]


def calculate_burstiness(text: str) -> Dict:
    """
    Calculate burstiness - the variation in sentence lengths.
    AI text tends to have low burstiness (uniform sentence lengths).
    Human text tends to have high burstiness (varied sentence lengths).
    """
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    sentences = [s for s in sentences if len(s.strip()) > 5]

    if len(sentences) < 2:
        return {'burstiness_score': 50.0, 'interpretation': 'insufficient_data'}

    lengths = [len(s.split()) for s in sentences]
    mean_len = np.mean(lengths)
    std_len = np.std(lengths)

    # Coefficient of variation as burstiness measure
    cv = (std_len / mean_len * 100) if mean_len > 0 else 0

    # Higher CV = more bursty = more likely human
    # Typical AI: CV < 30, Typical human: CV > 40
    if cv > 50:
        interpretation = 'highly_variable_human_like'
        human_probability = min(90, 50 + cv)
    elif cv > 35:
        interpretation = 'moderately_variable'
        human_probability = 40 + cv * 0.5
    elif cv > 20:
        interpretation = 'somewhat_uniform'
        human_probability = 30 + cv * 0.3
    else:
        interpretation = 'very_uniform_ai_like'
        human_probability = max(10, cv * 1.5)

    return {
        'burstiness_score': round(cv, 1),
        'mean_sentence_length': round(mean_len, 1),
        'std_sentence_length': round(std_len, 1),
        'sentence_count': len(sentences),
        'interpretation': interpretation,
        'human_probability': round(min(100, max(0, human_probability)), 1)
    }


def calculate_perplexity(text: str, max_length: int = 256) -> Dict:
    """
    Calculate perplexity using GPT-2.
    Lower perplexity = more predictable = more likely AI-generated.
    """
    tokenizer, model = _get_gpt2_model()

    if tokenizer is None:
        # Fallback: estimate based on text statistics
        return _estimate_perplexity(text)

    try:
        import torch

        encodings = tokenizer(text, return_tensors='pt', truncation=True, max_length=max_length)
        input_ids = encodings['input_ids']

        with torch.no_grad():
            outputs = model(input_ids, labels=input_ids)
            loss = outputs.loss.item()

        perplexity = math.exp(loss)

        # Interpret perplexity
        if perplexity < 20:
            interpretation = 'very_low_likely_ai'
            ai_probability = 85
        elif perplexity < 40:
            interpretation = 'low_possibly_ai'
            ai_probability = 65
        elif perplexity < 80:
            interpretation = 'moderate_uncertain'
            ai_probability = 40
        elif perplexity < 150:
            interpretation = 'high_likely_human'
            ai_probability = 25
        else:
            interpretation = 'very_high_human'
            ai_probability = 10

        return {
            'perplexity': round(perplexity, 2),
            'interpretation': interpretation,
            'ai_probability': ai_probability
        }
    except Exception as e:
        return _estimate_perplexity(text)


def _estimate_perplexity(text: str) -> Dict:
    """Rough perplexity estimate without a model."""
    words = text.split()
    unique_ratio = len(set(words)) / len(words) if words else 0
    avg_word_len = np.mean([len(w) for w in words]) if words else 0

    # Heuristic: AI text tends to have moderate vocab diversity, human is more varied
    estimated = 30 + unique_ratio * 100 + avg_word_len * 5
    return {
        'perplexity': round(estimated, 2),
        'interpretation': 'estimated',
        'ai_probability': round(max(10, min(90, 70 - unique_ratio * 60)), 1)
    }


def detect_ai_content(text: str) -> Dict:
    """
    Main AI content detection function.

    Returns per-paragraph AI probability scores,
    overall AI score, and supporting metrics.
    """
    start_time = time.time()

    classifier = _get_classifier()

    paragraphs = split_into_paragraphs(text)
    if not paragraphs:
        paragraphs = [text]

    paragraph_results = []
    all_ai_scores = []

    for p_idx, paragraph in enumerate(paragraphs):
        # RoBERTa classifier
        if classifier is not None:
            try:
                result = classifier(paragraph[:512])
                label = result[0]['label']
                confidence = result[0]['score']

                if label == 'LABEL_0':
                    # LABEL_0 = Real/Human
                    ai_probability = round((1 - confidence) * 100, 1)
                else:
                    # LABEL_1 = Fake/AI
                    ai_probability = round(confidence * 100, 1)
            except Exception:
                ai_probability = _fallback_ai_score(paragraph)
        else:
            ai_probability = _fallback_ai_score(paragraph)

        # Burstiness analysis for this paragraph
        burstiness = calculate_burstiness(paragraph)

        # Combine signals
        combined_score = ai_probability

        # Determine confidence level
        if combined_score >= 80:
            confidence_level = 'high'
            verdict = 'Likely AI-generated'
        elif combined_score >= 55:
            confidence_level = 'medium'
            verdict = 'Possibly AI-generated'
        elif combined_score >= 30:
            confidence_level = 'low'
            verdict = 'Likely human-written'
        else:
            confidence_level = 'very_low'
            verdict = 'Human-written'

        para_result = {
            'paragraph_index': p_idx,
            'text': paragraph[:200] + '...' if len(paragraph) > 200 else paragraph,
            'full_text': paragraph,
            'ai_probability': combined_score,
            'confidence_level': confidence_level,
            'verdict': verdict,
            'burstiness': burstiness,
            'word_count': len(paragraph.split()),
            'heatmap_color': _ai_score_to_color(combined_score)
        }
        paragraph_results.append(para_result)
        all_ai_scores.append(combined_score)

    # Overall document analysis
    overall_ai_score = round(np.mean(all_ai_scores), 1) if all_ai_scores else 0.0

    # Document-level burstiness
    doc_burstiness = calculate_burstiness(text)

    # Document-level perplexity
    doc_perplexity = calculate_perplexity(text[:1000])  # First 1000 chars

    # Overall verdict
    if overall_ai_score >= 75:
        overall_verdict = 'High probability of AI-generated content'
        overall_confidence = 'high'
    elif overall_ai_score >= 50:
        overall_verdict = 'Mixed content - likely contains AI-generated sections'
        overall_confidence = 'medium'
    elif overall_ai_score >= 25:
        overall_verdict = 'Mostly human-written with some AI-like patterns'
        overall_confidence = 'low'
    else:
        overall_verdict = 'Likely entirely human-written'
        overall_confidence = 'very_low'

    processing_time = round(time.time() - start_time, 2)

    return {
        'overall_ai_score': overall_ai_score,
        'overall_verdict': overall_verdict,
        'overall_confidence': overall_confidence,
        'paragraph_analysis': paragraph_results,
        'document_burstiness': doc_burstiness,
        'document_perplexity': doc_perplexity,
        'total_paragraphs': len(paragraphs),
        'high_risk_paragraphs': sum(1 for p in paragraph_results if p['ai_probability'] >= 70),
        'processing_time': processing_time,
        'model_used': 'roberta-base-openai-detector' if classifier else 'heuristic-fallback'
    }


def _fallback_ai_score(text: str) -> float:
    """Heuristic AI score when model isn't available."""
    words = text.split()
    sentences = re.split(r'(?<=[.!?])\s+', text)

    if not words or not sentences:
        return 30.0

    # Features that suggest AI text
    avg_sent_len = np.mean([len(s.split()) for s in sentences if s.strip()])
    vocab_diversity = len(set(w.lower() for w in words)) / len(words)
    avg_word_len = np.mean([len(w) for w in words])

    # AI text tends to: have moderate sentence lengths, moderate vocab diversity
    score = 30.0

    # Very uniform sentence lengths -> more AI-like
    sent_lengths = [len(s.split()) for s in sentences if s.strip()]
    if len(sent_lengths) > 1:
        cv = np.std(sent_lengths) / np.mean(sent_lengths) if np.mean(sent_lengths) > 0 else 0
        if cv < 0.25:
            score += 20
        elif cv < 0.4:
            score += 10

    # Moderate vocab diversity -> more AI-like
    if 0.45 < vocab_diversity < 0.65:
        score += 10

    # Longer average words -> slightly more AI-like
    if avg_word_len > 5.5:
        score += 5

    return min(90, max(10, score))


def _ai_score_to_color(score: float) -> str:
    """Convert AI score to color for heatmap."""
    if score >= 80:
        return '#EF4444'  # Red
    elif score >= 60:
        return '#F59E0B'  # Orange
    elif score >= 40:
        return '#FBBF24'  # Yellow
    elif score >= 20:
        return '#A3E635'  # Light green
    else:
        return '#10B981'  # Green
